name: talkbox
description: TalkBox Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  dio: ^5.4.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  intl: ^0.19.0
  file_picker: ^6.1.1
  video_player: ^2.8.2
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
